version: '3.3'
services:
  jenkins:
    image: elevengiants/jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
  nginx-artifacts:
    image: nginx
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./nginx-artifacts/nginx.conf:/etc/nginx/nginx.conf:ro
      - jenkins_home:/var/jenkins_home:ro
volumes:
  jenkins_home:
