version: '3.3'
services:
  jenkins:
    image: elevengiants/jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/log/jenkins:/var/log/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
  nginx-artifacts:
    image: nginx
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./nginx-artifacts/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/jenkins_home/artifacts:/www/data:ro
